package com.example.warehouse.demo.Controller;

import com.example.warehouse.demo.Model.Invoice;
import com.example.warehouse.demo.Repo.InvoiceRepository;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@RestController
@RequestMapping("/api/invoices")
@Tag(name = "2. Invoices Management", description = "Search, List, and Download Invoices")
public class InvoiceController {

    @Autowired
    private InvoiceRepository invoiceRepository;

    // --- 1. LIST ALL ---
    @GetMapping
    @Operation(summary = "List All Invoices", description = "Get the full history of generated invoices.")
    public List<Invoice> getAllInvoices() {
        return invoiceRepository.findAll();
    }

    // --- 2. SEARCH (New) ---
    @GetMapping("/search")
    @Operation(summary = "Search Invoices", description = "Find invoice by PO Number or Vendor Name.")
    public List<Invoice> searchInvoices(@RequestParam("query") String query) {
        String lowerQuery = query.toLowerCase();
        return invoiceRepository.findAll().stream()
                .filter(inv -> (inv.getPoNumber() != null && inv.getPoNumber().toLowerCase().contains(lowerQuery)) ||
                               (inv.getSenderName() != null && inv.getSenderName().toLowerCase().contains(lowerQuery)))
                .collect(Collectors.toList());
    }

    // --- 3. DELETE (New) ---
    @DeleteMapping("/{id}")
    @Operation(summary = "Delete Invoice", description = "Permanently remove an invoice from the database.")
    public ResponseEntity<String> deleteInvoice(@PathVariable UUID id) {
        if (invoiceRepository.existsById(id)) {
            invoiceRepository.deleteById(id);
            return ResponseEntity.ok("Invoice deleted successfully.");
        } else {
            return ResponseEntity.notFound().build();
        }
    }

    // --- 4. DOWNLOAD (Existing) ---
    @GetMapping("/download/{id}")
    @Operation(summary = "Download HTML Invoice", description = "Generates a professional HTML invoice file.")
    public ResponseEntity<ByteArrayResource> downloadInvoice(@PathVariable UUID id) {
        Invoice invoice = invoiceRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Invoice not found"));

        String statusColor = "APPROVED".equals(invoice.getStatus()) ? "green" : "red";

        String htmlContent = "<html><body style='font-family: Arial, sans-serif; padding: 40px; border: 1px solid #ddd; max-width: 800px; margin: auto;'>" +
                "<h1 style='text-align: center; color: #333;'>COMMERCIAL INVOICE</h1>" +
                "<hr>" +
                "<div style='display: flex; justify-content: space-between;'>" +
                    "<div><strong>From:</strong><br>" + invoice.getSenderName() + "<br>" + invoice.getSenderAddress() + "</div>" +
                    "<div><strong>To:</strong><br>" + invoice.getReceiverName() + "<br>" + invoice.getReceiverAddress() + "</div>" +
                "</div>" +
                "<br><hr><br>" +
                "<table style='width: 100%; text-align: left;'>" +
                    "<tr><th>Invoice ID:</th><td>" + invoice.getInvoiceId() + "</td></tr>" +
                    "<tr><th>Date:</th><td>" + invoice.getUploadedAt() + "</td></tr>" +
                    "<tr><th>Tracking #:</th><td>" + invoice.getTrackingNumber() + "</td></tr>" +
                    "<tr><th>PO Number:</th><td>" + invoice.getPoNumber() + "</td></tr>" +
                    "<tr><th>Weight:</th><td>" + String.format("%.2f", invoice.getWeightKg()) + " kg</td></tr>" +
                "</table>" +
                "<br><h2 style='text-align: center; border: 2px solid " + statusColor + "; color: " + statusColor + "; padding: 10px;'>" + 
                invoice.getStatus() + "</h2>" +
                "<p style='text-align: center; font-size: 12px; color: #777;'>Generated by AI Warehouse System</p>" +
                "</body></html>";

        ByteArrayResource resource = new ByteArrayResource(htmlContent.getBytes(StandardCharsets.UTF_8));

        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=invoice_" + id + ".html")
                .contentType(MediaType.TEXT_HTML)
                .contentLength(resource.contentLength())
                .body(resource);
    }
}